# Generated by Django 3.1.2 on 2021-11-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area51', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='hood_ref',
            new_name='Neighbourhood',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='prof_ref',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hood_ref',
            new_name='Neighbourhood',
        ),
    ]
